### PR TITLE
Update gradients

### LINKED ISSUE #2: Add suru gradient styles to each variant
Style the canvas output so it uses the suru gradient background for each variant, e.g.

Generic-Social_FL_1200x628

Generic-Social_F9-16_400x500

Generic-Social_FWide_800x418

Generic-Social_TSqr_800x800

Generic-Social_FMob_1080x1080

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Add gradient overlay styles for all banner backgrounds

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8057/?title=Ubuntu+for+the+internet+of+things&subtitle=From+smart+homes+to+smart+drones%2C+robots%2C+and+industrial+systems%2C+Ubuntu+is+the+new+standard+for+embedded+Linux.&illustration_url=https%3A%2F%2Fassets.ubuntu.com%2Fv1%2Fa70bfab2-Managed-apps_wht.svg&illustration_width=297&illustration_height=150&background=k8s
- Check that the gradients look in line with [the designs](https://app.zeplin.io/project/5efb66d1ae9030a1cd756466/dashboard?sid=5efb6853b230ad14982ed77b)

## Issue / Card

Fixes #2

### CODE REVIEW

**Comment by steverydz** [comment]
@waynecrosby I've assigned you to this so you can review it from a design/brand perspective.

**Comment by waynecrosby** [comment]
Thanks @steverydz 
A couple of comments about the Ubuntu gradient & suru:
1. The orange is looking a bit murky brown, could you make the grad go from the aubergine to #B9463C
2. There should be 3 suru elements, 2 white (3% & 5% opacity) and 1 black (5% opacity)
3. The balck suru is in the wrong position, see below where it should be
Screenshot 2020-07-06 at 13 02 41
Hopefully that should brighten it up, let me know if not clear. Thanks

**Comment by steverydz** [comment]
Thanks @waynecrosby 

I've updated the orange as requested, changed the opacity of the two white suru elements to 0.03 and 0.05, moved the position of the black suru element and changed it's opacity to 0.0.5

**Review by pmahnke — APPROVED** [review]
looking good... the only thing I have seen is when the h1 is short like 'Internet of Things' a few have the image pretty low... perhaps Wayne can comment on the right thing to do in this case.

**Comment by steverydz** [comment]
@pmahnke @waynecrosby the illustration is centred vertically and horizontally within it's container. I can make the image box the same height as the total text height. I'll do that in another PR though because it will require a fair bit of refactoring.

@waynecrosby If you're happy with these gradients I'll merge the PR

**Comment by waynecrosby** [comment]
@steverydz Not sure why but the gradient doesn't seem to be as bright as in Sketch? Can you try this orange to see if it lifts it #B94E47.
Also, as Peter said, when the copy is short the illustration on the taller banners stays too low, if you can try and centre it vertically in the gap left that would be great.
With 'Facebook & LinkedIn - 1200 x 628' when the copy is short as above, can you move the copy down to be more vertically centred as in this version 'Twitter wide - 800 x 418'. Thanks

**Comment by steverydz** [comment]
@waynecrosby I've updated the gradient orange.

For the text/image alignment I've made a new issue (https://github.com/canonical-web-and-design/tools.demo.haus/issues/14)

**Comment by steverydz** [comment]
@waynecrosby did you have any thoughts about the updated gradient?

**Comment by waynecrosby** [comment]
@steverydz It's looking much better, one thought I had was if you can have more aubergine so that the orange gradient starts further into the corner.
Screenshot 2020-07-08 at 10 05 58

**Comment by steverydz** [comment]
@waynecrosby I've updated it - what do you think?

**Comment by waynecrosby** [comment]
@steverydz The gradient should have 3 colours, are you using the below values?:
#2C001E --> #772953 --> #BA534A

In Sketch we use #e95420 orange but we finish it off canvas as it's too bright going to that in the corner, that is why I've given you the orange value above to use as that is what appears in the corner in Sketch. You can see what I mean in the image below:
Screenshot 2020-07-08 at 10 34 25

**Comment by steverydz** [comment]
@waynecrosby I've just pushed another update.

This is how it's constructed:

From bottom left to top right:
- #2c001e (0% to 62%)
- #772953 (62% to 94%)
- #ba534a (94% to 100%)

Then the overlays are:
- Top: rgba(255, 255, 255, 0.03)
- Bottom: rgba(255, 255, 255, 0.05)
- Top left: rgba(0, 0, 0, 0.05)

**Comment by waynecrosby** [comment]
@steverydz I think it's nearly there, I think the percentages are good, it's just that last orange shade we need to get right, could you try changing #ba534a (94% to 100%) to #c44e43 (94% to 100%). Thanks

**Comment by steverydz** [comment]
@waynecrosby done, how does it look?

**Comment by waynecrosby** [comment]
@steverydz I'm so sorry, can we try one more: #d1573c - if this one doesn't look right I think we revert to #ba534a

**Comment by steverydz** [comment]
@waynecrosby ok, updated

**Comment by waynecrosby** [comment]
@steverydz I think we revert to where you were as it's the closest to the Sketch file. Apologies for the back and forth:
#2c001e (0% to 62%)
#772953 (62% to 94%)
#ba534a (94% to 100%)

**Comment by steverydz** [comment]
@waynecrosby no worries, it's worth getting it right :)

I've updated as you said - if this is OK I'll get this merged.

**Comment by waynecrosby** [comment]
@steverydz Great, looking good!

**Comment by waynecrosby** [comment]
@steverydz Are you adjusting the illustration positioning on another issue?

**Comment by steverydz** [comment]
> @steverydz Are you adjusting the illustration positioning on another issue?

@waynecrosby Yes https://github.com/canonical-web-and-design/tools.demo.haus/issues/14

**Pull request merged**
